###
# setup
###
- name: install bundler
  gem: name={{item}} state=present
  with_items:
  - bundler
- name: run bundler
  bundler:
    state: present
    chdir: "{{override_dir}}"
- name: git update
  git: repo={{item.repo}} dest={{item.dest}} update=yes
  with_items:
  - { repo: "git@github.com:jackmoore/colorbox.git", dest: "{{colorbox_dir}}" }
  - { repo: "{{content_repo}}", dest: "{{blog_dir}}" }
###
# .gitignore
###
- name: "add items to .gitignore"
  lineinfile:
    name: "{{role_path}}/.gitignore"
    create: yes
    regexp: "^{{item}}$"
    line: "{{item}}"
  with_items:
  - files/colorbox
- name: .gitignore for content
  lineinfile:
    name: "{{blog_dir}}/.gitignore"
    regexp: "^{{item}}$"
    line: "{{item}}"
  with_items:
  - Gemfile
  - Gemfile.lock
  - _config.yml
  - _layouts
  - _sass
  - assets
  - img
  - index.md
  - js
###
# setup blog with jekyll
###
- name: "{{blog_dir}} exists?"
  stat: path={{blog_dir}}/_posts
  register: jekyll_done
- name: create site
  shell: "jekyll new blog"
  args:
    chdir: "{{role_path}}/files"
  when: not jekyll_done.stat.exists
- name: clean extra files from jenkins new
  file: path="{{item}}" state=absent
  with_fileglob:
  - "{{blog_dir}}/about.md"
  - "{{blog_dir}}/_posts/*-welcome-to-jekyll.markdown"
  when: not jekyll_done.stat.exists
###
# Colorbox
###
- name: colorbox directories
  file: path="{{blog_dir}}/{{item}}" state=directory
  with_items:
  - img
  - js/i18n
- name: link images from colorbox
  file:
    src: "{{item}}"
    dest: "{{blog_dir}}/img/{{item | basename}}"
    state: hard
  with_fileglob:
  - "{{colorbox_dir}}/{{colorbox_theme}}/images/*"
- name: link i18n from colorbox
  file:
    src: "{{colorbox_dir}}/i18n/jquery.colorbox-fi.js"
    dest: "{{blog_dir}}/js/i18n/jquery.colorbox-fi.js"
    state: hard
- name: link javascript from colorbox
  file:
    src: "{{item}}"
    dest: "{{blog_dir}}/js/{{item | basename}}"
    state: hard
  with_fileglob:
  - "{{colorbox_dir}}/*.js"
- name: download jquery
  get_url:
    url: https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js
    dest: "{{blog_dir}}/js/jquery.min.js"
###
# override files
###
- name: "override files"
  file: src="{{item}}" dest="{{blog_dir}}/{{item | basename}}" state=link
  with_fileglob:
  - "{{override_dir}}/*"
- name: "override with {{site}} (sync)"
  file:
    src: "{{override_dir}}/{{item}}"
    dest: "{{blog_dir}}/{{item}}"
    state: link
  with_items:
  - _layouts
  - _sass
  - assets
###
#  link with playbook_dir
- name: "link with playbook_dir"
  file: src="{{item.src}}" dest="{{item.dest}}" state=link
  with_items:
  - {src: "{{blog_dir}}", dest: "{{playbook_dir}}/blog"}
  - {src: "{{playbook_dir}}/images", dest: "{{role_path}}/files/images"}
###
###
# first jekyll build
###
- name: build site
  shell: "jekyll build"
  args:
    chdir: "{{blog_dir}}"
